
var db_lip = new Conection({
    servidor:'localhost',
    usuario:'Lip_Alonso',
    pass:'kfEq2Li-xwv3L]rP',
    baseDatos:'lip_dv',
    schema:[
        {"name":"customers","fields":[{"Field":"ID_COSTUMER","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"NAME","Type":"varchar(100)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"ID_CUSTOMER_TIPE","Type":"int(11)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"DIRECCION","Type":"varchar(300)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"REFERENCE","Type":"varchar(500)","Null":"NO","Key":"","Default":null,"Extra":""}]},
        {"name":"product_tipe","fields":[{"Field":"ID_PRODUCT_TIPE","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"NAME","Type":"varchar(50)","Null":"NO","Key":"","Default":null,"Extra":""}]},
        {"name":"buys","fields":[{"Field":"ID_BUY","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"DATE_EMMIT","Type":"date","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"ID_PROVIDEER","Type":"int(11)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"TOTAL","Type":"float","Null":"NO","Key":"","Default":null,"Extra":""}]},
        {"name":"buys_products","fields":[{"Field":"ID_BUY_PRODUCT","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"ID_BUY","Type":"int(11)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"ID_PRODUCT","Type":"int(11)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"CANT","Type":"float","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"PRICE_UNIT","Type":"int(11)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"PRINCE_TOTAL","Type":"int(11)","Null":"NO","Key":"","Default":null,"Extra":""}]},
        {"name":"products","fields":[{"Field":"ID_PRODUCTO","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"NAME","Type":"varchar(250)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"ID_PRODUCT_TIPE","Type":"int(11)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"UNID_ID","Type":"int(11)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"PRICE_UNIT","Type":"float","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"STOCK_TOTAL","Type":"float","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"ACTIVE","Type":"tinyint(1)","Null":"NO","Key":"","Default":null,"Extra":""}]},
        {"name":"recipe","fields":[{"Field":"ID_RECIPE","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"COST_TOTAL","Type":"int(11)","Null":"NO","Key":"","Default":null,"Extra":""}]},
        {"name":"provideers","fields":[{"Field":"ID_PROVIDEER","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"NAME","Type":"varchar(50)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"ID_PROVIDEER_TIPE","Type":"int(11)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"RUC","Type":"varchar(20)","Null":"NO","Key":"","Default":null,"Extra":""}]},
        {"name":"sales","fields":[{"Field":"ID_SALE","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"DATE_EMMIT","Type":"date","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"ID_STATUS","Type":"int(11)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"ID_CUSTOMER","Type":"int(11)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"TOTAL","Type":"float","Null":"NO","Key":"","Default":null,"Extra":""}]},
        {"name":"recipe_products","fields":[{"Field":"ID_RECIPE_PRODUCT","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"ID_RECIPE","Type":"int(11)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"RESULT_INGREDIENT","Type":"tinyint(1)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"ID_PRODUCT","Type":"int(11)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"CANT","Type":"float","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"COST_UNIT","Type":"float","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"COST_TOTAL","Type":"float","Null":"NO","Key":"","Default":null,"Extra":""}]},
        {"name":"users","fields":[{"Field":"ID_USER","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"NAME","Type":"varchar(50)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"PASSWORD","Type":"varchar(50)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"ID_CLASS","Type":"int(11)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"ACTIVE","Type":"tinyint(1)","Null":"NO","Key":"","Default":"1","Extra":""}]},
        {"name":"sales_payments","fields":[{"Field":"ID_SALE_PAY","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"ID_SALE","Type":"int(11)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"ID_PAY","Type":"int(11)","Null":"NO","Key":"","Default":null,"Extra":""}]},
        {"name":"unids","fields":[{"Field":"ID_UNID","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"NAME","Type":"varchar(50)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"SIMBOL","Type":"varchar(10)","Null":"NO","Key":"","Default":null,"Extra":""}]},
        {"name":"payments","fields":[{"Field":"ID_PAYMENT","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"DATE_EMMIT","Type":"date","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"TOTAL","Type":"float","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"ID_METHOD_PAY","Type":"int(11)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"ID_TAG_PAY","Type":"int(11)","Null":"NO","Key":"","Default":null,"Extra":""}]},
        {"name":"sales_products","fields":[{"Field":"ID","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"ID_SALE","Type":"int(11)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"ID_PRODUCT","Type":"int(11)","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"CANT","Type":"float","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"PRICE_UNIT","Type":"float","Null":"NO","Key":"","Default":null,"Extra":""},{"Field":"PRICE_TOTAL","Type":"float","Null":"NO","Key":"","Default":null,"Extra":""}]},

    ]
});

conectionOfUsers = db_lip;




