
$(document).ready(function() {

  new Pag_Base({

    success:({userData,pageData})=>{

        new CrudsGroup({
          userData,parent:pageData.body,
          layers:[
            {
              grid:{
                items:[
                  {name:"prnt-buy"},
                  {name:"prnt-pay-md"},
                ],
              }
            },
            {modal:{parent:"prnt-pay-md",name:"md-pay"}},
            //-----buy-----
            {
              crud:{
                parent:"prnt-buy",name:"cr-buy",
                title:"compra",schema:sch_buys,
                panels:[
                  {
                    tipe:"form",title:"informacion general",col:4,
                    fieldsSet:[
                      {value:"date",state:"edit"},
                      {value:"state",state:"edit"},
                      {value:"provideer",state:"edit"},
                      {value:"total",state:"show"},
                    ],
                  },
                  {
                    tipe:"form",head:false,col:8,
                    fieldsSet:[
                      {action:"div",name:"prnt-buy-stps"},
                    ],
                  },
                  {
                    tipe:"form",title:"total",
                    fieldsSet:[
                      {value:"total",state:"show",showBox:bx_moneyh1},
                    ],
                  },
                ],
              }
            },
            {
              steps:{
                parent:"prnt-buy-stps",
                items:[
                  {name:"stp-pays",title:"pagos"},
                  {name:"stp-products",title:"items"},
                ],
              }
            },
            //----products------
            {
              crud:{
                parent:"stp-products",name:"cr-buy-products",
                title:"lista de compras",schema:sch_buys_products,
                panels:[
                  {
                    tipe:"table",h:600,
                    fieldsSet:[
                      {value:"item",state:"edit"},
                      {value:"cant",state:"edit"},
                      {value:"costUnit",state:"edit"},
                      {value:"costTotal",state:"edit"},
                    ],
                  }
                ],
              }
            },
            //-----pays------
            {
              crud:{
                parent:"stp-pays",name:"cr-buy-pays",h:0,
                title:"lista de pagos",schema:sch_buys_payments,
                selects:[
                  {table:sch_buys_payments.table,field:"ID_PAY"},
                  {table:sch_pays.table,field:"TOTAL"},
                  {table:sch_accounts.table,field:"NAME"},
                ],
                joins:[
                  {
                    main:{table:sch_buys_payments.table,field:"ID_PAY"},
                    join:{table:sch_pays.table,field:"ID_PAY"},
                    tipe:"LEFT",
                  },
                  {
                    main:{table:sch_pays.table,field:"ID_ACCOUNT"},
                    join:{table:sch_accounts.table,field:"ID_ACCOUNT"},
                    tipe:"LEFT",
                  }
                ],
                panels:[
                  {
                    tipe:"table",head:false,
                    fields:[
                      {name:"total",box:{...bx_money},select:"TOTAL",attributes:[{name:"style",value:"min-width:100px"}]},
                      {name:"cuenta",box:{...bx_shw},select:"NAME",attributes:[{name:"style",value:"min-width:150px"}]},
                    ],
                    fieldsSet:[
                      //{value:"idBuy",state:"show"},
                      //{value:"idPay",state:"show"},
                    ],
                  }
                ],
              }
            },
            {
              crud:{
                parent:"md-pay",name:"cr-buy-pay",
                title:"pago",schema:sch_pays,
                panels:[
                  {
                    tipe:"form",head:false,
                    fieldsSet:[
                      {value:"date",state:"edit"},
                      {value:"account",state:"edit"},
                      {value:"total",state:"edit"},
                      {value:"tag",state:"edit"},
                      {value:"income",state:"edit"},
                    ],
                  }
                ],
              }
            }
          ],
          conections:[
            {
              masterName:"cr-buy",
              masterSelect:"ID_BUY",
              event:"list",
              maidName:"cr-buy-products",
              maidSelect:"ID_BUY",
            },
            {
              masterName:"cr-buy",
              masterSelect:"ID_BUY",
              event:"list",
              maidName:"cr-buy-pays",
              maidSelect:"ID_BUY",
            },
            {
              masterName:"cr-buy-pays",
              masterSelect:"ID_PAY",
              event:"tableForm",
              maidName:"cr-buy-pay",
              maidSelect:"ID_PAY",
            },
          ],
        });

    }
  });
  

});
